# Site settings
title: Krad Weblog
tagline: Nothing to do here
description: > # this means to ignore newlines until "baseurl:"
  An awesome description for my site.
keywords: [krad, blog, tunglt, tung le, thanh tung]
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tunglt.com" # the base hostname & protocol for your site, e.g. http://example.com
non-ssl-url: "http://www.tunglt.com"

permalink: /:year/:month/:title/

# Author
author:
  name: Krad
  url: https://twitter.com/tungkradle
  email: tungkradle@gmail.com

# Build settings 
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: krad
plugins:
  - jekyll-feed
#  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed

# Custom vars
version: 3.4.1
github:
  repo: https://github.com/kradnozd/kradblog
fb_app_id: 334951299891652
google_trackid: "UA-88456593-1"

# Fix bug 
excerpt_separator: ""