# Site settings
title: Krad Weblog
tagline: Nothing to do here
description: > # this means to ignore newlines until "baseurl:"
  An awesome description for my site.
keywords: [krad, blog, tunglt, tung le, thanh tung]
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tunglt.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:year/:month/:title/

# Author
author:
  name: Krad
  url: https://twitter.com/tungkradle
  email: kradnozd@gmail.com

# Build settings markdown: kramdown
theme: krad
gems:
  - jekyll-feed
#  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed

# Custom vars
version: 3.3.1
github:
  repo: https://github.com/kradnozd/kradblog
fb_app_id: 334951299891652

# Fix bug 
excerpt_separator: ""